Reveal.initialize({
    hash: true,
    slideNumber: 'c/t',
    showSlideNumber: 'all',
    transition: 'slide',
    transitionSpeed: 'default',
    backgroundTransition: 'fade',
    width: 1280,
    height: 720,
    margin: 0.02,
    center: false,
    controls: true,
    controlsTutorial: false,
    progress: true,
    touch: true,
    keyboard: true,
    overview: true,
    hideInactiveCursor: true,
    hideCursorTime: 2000,
});
