Reveal.initialize({
    hash: true,
    slideNumber: 'c/t',
    showSlideNumber: 'all',
    transition: 'fade',
    transitionSpeed: 'slow',
    backgroundTransition: 'fade',
    width: 1280,
    height: 720,
    margin: 0.04,
    center: true,
    controls: true,
    controlsTutorial: false,
    progress: true,
    touch: true,
    keyboard: true,
    overview: true,
});
